name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
    
    - name: Install minimal stable with clippy and rustfmt
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libpipewire-0.3-dev
        
    - name: Install Windows dependencies (vcpkg)
      if: runner.os == 'Windows'
      run: |
        vcpkg install --triplet x64-windows
        New-Item -ItemType Junction -Path "$env:VCPKG_INSTALLATION_ROOT\installed" -Target "vcpkg_installed" -Force
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $env:GITHUB_ENV
    - name: Build Workspace
      run: cargo build --workspace
      
    - name: Run tests
      run: cargo test --workspace
      
    - name: Run Clippy
      run: cargo clippy --workspace -- -D warnings
      
    - name: Format Check
      run: cargo fmt --all -- --check
