name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v7
    
    - name: Install minimal stable with clippy and rustfmt
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libpipewire-0.3-dev libavcodec-dev libavformat-dev libavutil-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev clang pkg-config
        
    - name: Setup vcpkg and install dependencies
      if: runner.os == 'Windows'
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: '5e5d0e1cd7785623065e7713fcce07022cae57ae' # or appropriate commit
        runVcpkgInstall: true
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Create vcpkg_installed Junction
      if: runner.os == 'Windows'
      run: |
        New-Item -ItemType Junction -Path "$env:GITHUB_WORKSPACE\vcpkg\installed" -Target "$env:GITHUB_WORKSPACE\vcpkg_installed" -Force
        echo "VCPKG_ROOT=$env:GITHUB_WORKSPACE\vcpkg" >> $env:GITHUB_ENV
    - name: Build Workspace
      run: cargo build --workspace > build.log 2>&1
      
    - name: Upload log to branch on failure
      if: failure()
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git checkout -b ci-logs
        git add build.log
        git commit -m "Upload log"
        git push -f origin ci-logs
    - name: Run tests
      run: cargo test --workspace
      
    - name: Run Clippy
      run: cargo clippy --workspace -- -D warnings
      
    - name: Format Check
      run: cargo fmt --all -- --check
